boostcampwm-2024/web31-BooLock

- apps/server/package.json
- apps/server/src/app.ts
- apps/server/src/config/dbConnection.ts
- apps/server/src/controllers/exampleController.ts
- apps/server/src/docs/swagger-output.json
- apps/server/src/docs/swagger.ts
- apps/server/src/docs/swaggerAutogen.ts
- apps/server/src/models/exampleModel.ts
- apps/server/src/routes/v1/exampleRoute.ts
- apps/server/src/services/exampleService.ts
- pnpm-lock.yaml
- Cloud DB for MongoDB 세팅
- mongoDB 연동
- 샘플용 crud 코드 생성
- 스웨거 문서 관련 수정
- boolock_test 라는 vpc를 하나 만들고, 하위에 public, private 서브넷을 하나씩 만들었습니다. 
- mongoDB는 private subnet에 위치시켰습니다.
- 그럼 왜 public도 만들었는지? : 해당 vpc는 이후 테스트용 배포버전에서도 사용하기 위해서 server 인스턴스를 위치시킬 공간으로 만들어두었습니다.
- 약간의 트러블슈팅 과정이 있었으나 결론적으로 ssl vpn을 생성하여 vpn 접속 후 db 연동을 하는 방식으로 진행하게 되었습니다.
- vpn 접속 시간에 대한 유효 시간도 존재하고, otp로 2차 인증까지 해야하는 불편한 세팅과정을 필요케하여 죄송합니다ㅠㅠ..
- 연동 세팅은 슬랙 팀 dm에 올린 메시지대로 진행해주시면 됩니다:) (env 설정값에 대해 약간 변동사항이 있어서 이미 설정하신 분들은 확인 후 다시 설정해주시길 바랍니다)
- env 파일 설정은 변경사항이 있을 때마다 말씀드리겠습니다. 
``` jsx
// apps/server/app.tsx
mongoose.connect(
process.env.MONGO_URI||""
)
.then(() => console.log('MongoDB connected'))
.catch((err) => { console.log(err) })
```
- db 연동에 대한 코드는 위 코드가 전부입니다.
- 코드 볼륨이 크지 않아 별도의 db 연동을 하는 파일을 추가적으로 만들지 않아도 되겠다고 …
> [#67] 백엔드 mongoDB 연동

- apps/server/package.json
- apps/server/src/config/dbConnection.ts
- pnpm-lock.yaml
- cloud DB -> server instance 내 DB 설정으로 변경
-  ssh 설정 및 db 연동 코드 추가
[(감사합니다 web03팀 캠퍼분들..)](https://github.com/boostcampwm-2024/web03-CorinEE/wiki/%5BBE%5D-ssh%ED%84%B0%EB%84%90%EB%A7%81%EC%9C%BC%EB%A1%9C--db%EC%97%B0%EA%B2%B0) (아키텍쳐 이미지도 추후 바꿀게요..)
- 기존에 ncp의 cloud DB for MongoDB 라는 클라우드 DB를 사용하는 방식에서, private server instacne를 생성하고 이 내부에 mongoDB를 구축 한 후 ssh 터널링을 통해 db를 연동하는 방식으로 변경하였습니다.
- 기존의 db 연동 코드를 사용하려면, 터미널창에서 ssh 터널링 환경으로 세팅해두고 연결을 시도해야합니다. 
- 계속 개발을 진행할 때마다, 로컬에서 터널링을 설정하고 연결해야하는 번거로움을 없애고자 tunnel-ssh 패키지를 활용하여 아예 서버를 실행할 때마다 ssh 터널링을 통해 db에 접근할 수 있게 설정해주었습니다.
<추후 작성... 예정..>
> [#83] db 연동 구조 변경 및 코드 수정

- apps/server/src/controllers/exampleController.ts
- apps/server/src/controllers/workspaceController.ts
- apps/server/src/docs/swagger-output.json
- apps/server/src/docs/swagger.ts
- apps/server/src/docs/swaggerAutogen.ts
- apps/server/src/routes/v1/exampleRoute.ts
- apps/server/src/routes/v1/workspaceRoute.ts
- swagger autogen이 주석처리 설정을 못읽어오던 오류 해결
- 주석처리 위치를 controller에서 router로 옮겼습니다.
- 기존 example 코드들은 바로 `/` 경로로 넘어갔기에 controller 함수 내에서의 주석처리를 잘 읽어왔던 것 같은데, `/workspace/` 경로를 한번 끼고 나니 workspace controller 함수 내 스웨거 설정 주석은 잘 못 읽어오는 것 같습니다.
```js
workspaceRouter.post(
'/',
workspaceController.createNewWorkspace
/* 
#swagger.summary = '새로운 워크스페이스 생성'
#swagger.description = '새로운 워크스페이스를 생성합니다.'
...
)
```
- 이런식으로 아예 router에서 controller 함수 매핑해줄 때, controller 설정 뒤에 바로 스웨거 설정 주석을 덧붙여주는 것으로 변경했습니다.
> [🚨 !HOTFIX!] swagger autogen이 주석처리 설정을 못읽어오던 오류 해결

- apps/server/Dockerfile
- apps/server/src/config/dbConnection.ts
- db연동시 로컬/배포환경 분리를 위한 로직 추가
- server docker파일 수정
- db연동하는 코드를 로컬환경만 고려한 코드로 작성해두었습니다.
- ssh터널링을 이용하여 private db server에 접근해 연동하는 방식
- 배포환경에서는 바로 터널링 없이 private db 서버로 연동시도를 하면 되기에 해당 로직을 추가하였습니다.
- client 배포 이미지는 nginx를 이용한 배포인지라, 정적인 파일로 이루어져 있어 dist 폴더 내용들만 카피하고 배포하면 되었습니다.
- 하지만, server 배포 이미지는 정적인 파일을 배포하는 것이 아니기에 정적인 형식처럼 배포하던 스크립트를 수정하였습니다.
> [#96] db연동시 로컬/배포환경 분리를 위한 로직 추가

- .github/workflows/boolock-dev-cicd.yml
아니 pr 이름 만들어질 줄 알고 깃허브 액션 테스트라고 한건데 브랜치가 만들어졌네요 당황스럽네요
- 깃허브 액션 스크립트 제작
```yml
on:
push:
branches: ['dev']
pull_request:
branches: ['dev']
```
- 이번에 만든 action 스크립트는 dev용으로만 만들었습니다. 즉, 테스트 서버에 올라가는 부분에 대한 action 스크립트를 작성한 것입니다.
- main으로 올라갈때에 대한 스크립트는 메인 서버 구축 및 배포 환경이 갖추어졌을 때 다시 제작하도록 하겠습니다.
```yml
jobs:
build:
...
deploy:
needs: build
```
- build와 deploy로 나누어 실행됩니다.
- build는 dev 실행이 잘 되는지, docker 이미지가 잘 빌드 되는지 확인합니다.
- deploy는 build가 오류 없이 실행된 후 실행됩니다. 실제 저희 테스트 서버에 자동으로 배포해주는 역할을 합니다.
- build과정은 아래와 같이 이루어집니다.
```yml
steps:
- uses: actions/checkout@v4
- name: Set up Node.js
uses: actions/setup-node@v4
with:
node-version: '20.x'
- name: Install Pnpm
run: npm install -g pnpm
- name: Package install with pnpm
run: pnpm install:all
- name: Set BE .env
run: |
echo "MONGO_URI=\"${{ …
```
> 깃허브 액션 테스트

- README.md
- apps/client/src/entities/home/WorkspaceItem.tsx
- apps/client/src/entities/workspace/WorkspaceNameInput.tsx
- apps/client/src/shared/api/workspaceApi.ts
- apps/client/src/shared/hooks/index.ts
- apps/client/src/shared/hooks/queries/useDeleteWorkspace.ts
- apps/client/src/shared/hooks/queries/useGetWorkspace.ts
- apps/client/src/shared/hooks/queries/useUpdateWorkspaceName.ts
- apps/client/src/shared/store/useModalStore.ts
- apps/client/src/shared/ui/button/SquareButton.tsx
- apps/client/src/shared/ui/index.ts
- apps/client/src/shared/ui/loading/Loading.tsx
- apps/client/src/shared/ui/loading/Spinner.tsx
- apps/client/src/widgets/home/WorkspaceContainer.tsx
- apps/client/src/widgets/home/WorkspaceList.tsx
- apps/client/src/widgets/home/WorkspaceModal.tsx
- apps/server/src/controllers/workspaceController.ts
- apps/server/src/routes/v1/workspaceRoute.ts
- apps/server/src/services/workspaceService.ts
- 워크스페이스 삭제 기능 구현
- API 명세
- method : DELETE , end-point : "/workspace
- headers : { user-id : 유저 아이디 }
- query : ?workspaceId=워크스페이스 아이디
- workspace가 존재하지 않으면 : 404 에러
- 그외 에러 : 500 에러
- Swagger 명세 작성
- Trashcan Icon 클릭 시 modal Content 및 modal Action을 등록
```ts
const handleOnclick = () => {
setModalContent(`${title}을(를)
삭제하겠습니까?`);
setModalAction(() => {
mutate(workspaceId);
});
onOpen();
};
```
- 워크스페이스 삭제 요청 시 모달의 `isLoading`을 `true`로 바꾸어 모달의 삭제 버튼이 여러번 클릭되어 api가 여러 번 요청 되는 현상을 방지했습니다.
- 워크스페이스 삭제 성공 시 getWorkspaceList의 캐시 데이터를 refetch하도록 했습니다.
```tsx
onSuccess: () => {
queryClient.invalidateQueries({ queryKey: ['getWorkspaceList'] });
toast.success('워크스페이스 삭제 성공');
},
```
- 모달 삭제 버튼 클릭 시 삭제 요청 대기 시간동안 로딩위젯이 나오도록 변경했습니다.
- PR 리뷰 반영
-  모달의 `isLoading`은 아직 변경하지 않은 상태입니다.
- 불필요한 코드 삭제
- 모달 …
> [#5] 워크스페이스 삭제 기능 구현 (PR 리뷰 반영)

- apps/client/package.json
- apps/client/src/widgets/workspace/PreviewBox.tsx
- pnpm-lock.yaml
- HTML/CSS 코드를 아래의 형식처럼 코드 블록으로 확인할 수 있다.
- 코드 편집기 라이브러리 CodeMirror 활용 
- 활용할 라이브러리 및 extension 선언
```
import CodeMirror from '@uiw/react-codemirror';
import { html } from '@codemirror/lang-html';
import { css } from '@codemirror/lang-css';
``` 
- 태그에 속성 선언
- value: 표시될 초기 코드 값
- height: 에디터의 높이
- extensions: 확장 기능 추가하는 배열
- theme: 편집기의 테마
```
<CodeMirror value={htmlCode} height="100%" extensions={[html()]} theme="light" />
```
- 최종
```
{activeTab === 'html' && (
<CodeMirror value={htmlCode} height="100%" extensions={[html()]} theme="light" />
)}
{activeTab === 'css' && (
<CodeMirror value={cssCode} height="100%" extensions={[css()]} theme="light" />
)}
```
> [#130] 사용자는 HTML/CSS 코드를 코드 블록으로 확인할 수 있다.

- apps/client/src/entities/workspace/RedoButton.tsx
- apps/client/src/entities/workspace/UndoButton.tsx
- apps/client/src/shared/store/index.ts
- apps/client/src/shared/store/useWorkspaceStore.ts
- apps/client/src/widgets/workspace/WorkspaceContent.tsx
- undo/redo 기능 추가
- 기본적으로 캔버스에 올라가있는 svg
- 기본 설정 블록들이 뒤로가기 누르면 분리되고 사라지는 버그 수정
- Blockly.WorkspaceSvg 클래스 내에는 undo 메소드가 있습니다. (정확히는 상속받아 사용하는 클래스인 workspace에 있습니다.)
- 이 메소드는 public 메소드이기에 undo/redo 컴포넌트에서 저희가 만든 workspace 인스턴스에 접근할 수만 있다면 쉽게 동작할 수 있겠다고 생각했습니다.
- zustand를 이용해 workspaceStore를 만들었습니다.
```js
import { create } from 'zustand';
import * as Blockly from 'blockly/core';
type Tworkspace = {
workspace: Blockly.WorkspaceSvg | null;
setWorkspace: (newWorkspace: Blockly.WorkspaceSvg) => void;
};
export const useWorkspaceStore = create<Tworkspace>((set) => ({
workspace: null,
setWorkspace: (newWorkspace: Blockly.WorkspaceSvg) => {
set({ workspace: newWorkspace });
},
}));
```
- 이를 외부 undo/redo 컴포넌트에서 workspace가 null이 아닐 시 undo/redo 동작이 먹힐 수 있게 동작함수를 할당해주었습니다.
```js
...
const { workspace …
```
> [#34] undo/redo 기능 추가

- apps/client/src/shared/api/workspaceApi.ts
- apps/client/src/shared/hooks/queries/useSaveWorkspace.ts
- apps/client/src/shared/hooks/queries/useUpdateWorkspaceName.ts
- apps/client/src/shared/types/workspaceType.ts
- apps/client/src/widgets/workspace/WorkspaceContent.tsx
- apps/server/src/services/workspaceService.ts
- useUpdateWorkspaceName 커스텀 훅 수정
- workspace에 블록 load 하는 방식 수정
```tsx
onSuccess: (data) => {
toast.success('워크스페이스 이름이 변경되었습니다.');
queryClient.invalidateQueries({ queryKey: workspaceKeys.detail(data.workspaceId) });
queryClient.invalidateQueries({ queryKey: workspaceKeys.list() });
},
```
- 서버에서 반환하는 업데이트된 workspace 속성이 전부 파스칼 케이스로 변경됨
- data의 속성이 파스칼 케이스로 변경됨에 따라 `workspace_id` => `workspaceId`로 변경했습니다.
```tsx
useEffect(() => {
if (!workspace || canvasInfo.length === 0) {
return;
}
Blockly.serialization.workspaces.load(JSON.parse(canvasInfo), workspace);
}, [workspace, canvasInfo]);
```
- useEffect 의존성 배열에 `workspace`만 포함되어 워크스페이스 페이지 로딩 시 `canvasInfo`의 데이터가 변경되어도 `workspace`에 반영되지 않는 문제가 있어 의존성 배열에 `canvasInfo`를 추가하였습니다.
> [#157] 워크스페이스 이름 변경 시 상태 관리 미적용, 워크스페이스에 저장된 블록이 있음에도 새로 고침 시 초기화 되는 문제 해결

- .github/workflows/boolock-dev-cicd.yml
- .gitignore
- apps/client/Dockerfile
- apps/client/nginx.conf
- docker-compose.yml
- ssl 인증서 발급
- https 환경으로 배포 https://boolock.site/
- https://certbot.eff.org/ 여기서 무료로 ssl 인증서 발급해준다길래 사용했습니다.
- 저희 서버 ssh 터미널에서 아래와 같은 명령어를 치고 인증서를 발급받았습니다.
```
sudo apt install certbot
sudo certbot certonly --standalone -d boolock.site
```
- 발급받은 인증서는 `/etc/letsencrypt/live/boolock.site/` 경로로 설치됩니다.
- apps/client/ssl 경로 내에 인증서 파일과 키를 카피해두고 ingnore 설정해주었습니다.
- 인증서를 다운받고 위치시키는 것도 certbot 컨테이너로 해서 docker로 할 수 있고, 캐시로 저장도 되나 그냥 서버를 변경하지 않으니 서버 내에서 발급받고 copy해와서 사용하기로 결정했습니다.
- https 환경으로 배포하기 위해 nginx 파일과 client docker파일을 수정하였습니다.
```
// nginx
server {
listen 80;
server_name boolock.site;
location / {
return 301 https://$host$request_uri;
}
}
```
- 80번 포트로 들어오는 요청들은 https 경로로 리다이렉션되게 해두었습니다.
```
// nginx
server {
listen 443 ssl;
server_name boolock.site;
ssl_certificate …
```
> [#165] https 환경으로 배포

- apps/client/src/entities/home/NotHoveredEmptyWorkspace/NotHoveredEmptyWorkspace.tsx
- apps/client/src/entities/home/WorkspaceLoadError/WorkspaceLoadError.tsx
- apps/client/src/pages/NotFound/NotFound.tsx
- apps/client/src/shared/ui/logo/Logo.tsx
- apps/client/src/shared/ui/modal/ModalConfirm.stories.tsx
- apps/client/src/widgets/home/HomeHeader/HomeHeader.tsx
- apps/client/src/widgets/home/WorkspaceModal/WorkspaceModal.tsx
- 이미지 경로 수정
- 안 쓰는 프로필이미지 요소 삭제
```tsx
```
- 경로를 상대경로에서 절대경로로 변경해주니 잘 동작했습니다 ㅎㅎ
- 저희 우측 상단에 안 쓰는 프로필 이미지 요소 삭제했습니다.
> [#178] 워크스페이스화면에서 로고 이미지가 깨져보이는 오류 해결

- apps/client/src/core/styleFlyout.ts
- apps/client/src/shared/blockly/htmlCodeGenerator.ts
- apps/client/src/shared/blockly/index.ts
- apps/client/src/widgets/workspace/WorkspaceContent/WorkspaceContent.tsx
- html generator 할 때 잘 안먹힘 - class 블록에 특정 오류 발생 추정
- 블록이 body를 벗어나도 프리뷰에 계속 보임
- html 블록에 포함된 것만 처리하게 변경하였습니다.
```
// 최상위 블록 (getRootBlock: Blockly의 블록 트리 탐색 함수)
const topBlock = block.getRootBlock();
// 최상위 블록이 html 블록이 아니면 빈 문자열 반환
if (topBlock.type !== addPreviousTypeName('html')) {
return '';
}
```
- 또한 클래스 블록에 대해 변경처리를 위해 workspace내의 모든 블럭을 기반으로 코드 재생성하는 함수를 만들었습니다.
```js
// 전체 코드 생성 함수
export const generateFullCode = (workspace: Blockly.Workspace) => {
const topBlockList = workspace.getTopBlocks(true);
const codeList = topBlockList.map((block) => {
try {
return htmlCodeGenerator.blockToCode(block) || '';
} catch (e) {
console.error(`블록 ${block.type} 처리 중 오류 발생:`, e);
return '';
}
});
return codeList.join('\n');
};
```
- before
- after
- 지금 블록이 html 내부가 아니라 밖으로가면 빈 값으로 처리되는 부분이 있는데, …
> [#176] html generator 적용 에러

- apps/client/src/shared/utils/cssCategoryList.ts
- apps/client/src/widgets/workspace/PreviewBox/PreviewBox.tsx
#187 
- 폰트 선택 기능 추가
총 6개의 폰트 google font에서 한글 폰트 중 weight가 3개 이상인(Nanum Gothic 제외) 폰트를 선정했습니다. 굵기는 300, 400, 700 중 선택할 수 있도록 옵션을 제공했습니다.
```typescript
'Noto Sans KR',
'Noto Serif KR',
'Nanum Gothic',
'Gaegu',
'IBM Plex Sans KR',
'Gothic A1',
```
previewBox에서 iframe head에 구글 폰트를 사용할 때 필요한 link를 넣어주었습니다.
```typescript
const googleFontsLinksCode = `
<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link href="https://fonts.googleapis.com/css2?family=Gaegu:wght@300;400;700&family=Gothic+A1:wght@300;400;700&family=IBM+Plex+Sans+KR:wght@300;400;700&family=Nanum+Gothic:wght@400;700&family=Noto+Sans+KR:wght@100..900&family=Noto+Serif+KR:wght@200..900&display=swap" rel="stylesheet" />
`;
const finalCssCode = …
```
> [#187] 폰트 선택 기능 추가

- apps/client/src/core/styleFlyout.ts
- apps/client/src/shared/blockly/createCssClassBlock.ts
- apps/client/src/shared/blockly/cssCodeGenerator.ts
- apps/client/src/shared/hooks/queries/useGetWorkspace.ts
- apps/client/src/shared/store/useClassBlockStore.ts
- apps/client/src/shared/utils/boolockConstants.ts
- apps/client/src/shared/utils/index.ts
- apps/client/src/widgets/workspace/WorkspaceContent/WorkspaceContent.tsx
- apps/client/src/widgets/workspace/css/CssPropsSelectBoxHeader/CssPropsSelectBoxHeader.tsx
- 클래스 블록 생성 시  `CSS_` 라는 접두사를 붙였습니다.
- 워크스페이스 페이지에서 변경사항이 없음에도 변경사항이 있다고 하는 문제를 해결했습니다.
```ts
// CSS 클래스명에 접두사를 붙이는 메서드
addPrefixToClassName(className: string) {
const CSS_CLASS_PREFIX = 'CSS_';
return `${CSS_CLASS_PREFIX}${className}`;
}
```
```ts
export const CSS_CLASS_PREFIX = 'CSS_';
export const addPrefixToCssClassName = (className: string) => {
return className.startsWith(CSS_CLASS_PREFIX) ? className : `${CSS_CLASS_PREFIX}${className}`;
};
export const removeCssClassNamePrefix = (className: string) => {
return className.startsWith(CSS_CLASS_PREFIX)
? className.replace(CSS_CLASS_PREFIX, '')
: className;
};
```
```ts
const handleAutoConversion = (event: Blockly.Events.Abstract) => {
if (
event.type === Blockly.Events.BLOCK_CREATE ||
event.type === Blockly.Events.BLOCK_MOVE || …
```
> [#188] 클래스 블록 생성 시 blockly 기본 블록이 생성되는 문제 해결, 워크스페이스 초기 로딩 시 변경사항 감지 문제 해결

- apps/client/src/core/fixedFlyout.ts
#133 
- flyout 크기 고정
- workspace와 flyout 사이에 연결되어 있던 zoom 비율을 끊었습니다.
아직 img 태그랑 a 태그가 없는 상태라서 문제가 없는데 ... 두 태그가 생기면 flyout 좌우로 스크롤 되도록 만들겠습니다...?
> flyout 크기 고정

- apps/client/src/app/index.css
- apps/client/src/core/styleFlyout.ts
- apps/client/src/entities/workspace/SaveButton/SaveButton.tsx
- apps/client/src/entities/workspace/WorkspaceNameInput/WorkspaceNameInput.tsx
- apps/client/src/shared/code-highlighter/components/CodeViewer.tsx
- apps/client/src/shared/hooks/queries/useCreateWorkspace.ts
- apps/client/src/shared/hooks/queries/useGetWorkspace.ts
- apps/client/src/shared/hooks/queries/useSaveWorkspace.ts
- apps/client/src/shared/hooks/queries/useUpdateWorkspaceName.ts
- apps/client/src/shared/store/useClassBlockStore.ts
- apps/client/src/shared/store/useWorkspaceStore.ts
- apps/client/src/shared/utils/capturePreview.ts
- apps/client/src/shared/utils/index.ts
- apps/client/src/widgets/workspace/WorkspaceContent/WorkspaceContent.tsx
- apps/client/src/widgets/workspace/css/CssPropsSelectBoxHeader/CssPropsSelectBoxHeader.tsx
- apps/server/package.json
- apps/server/src/services/workspaceService.ts
- pnpm-lock.yaml
#202 
#207
#208
#209
#210
- 워크스페이스 썸네일 이미지 깨짐 문제 해결
- 워크스페이스 썸네일 캡처 시 CSS 적용 안되는 문제 해결
- 워크스페이스 이름 변경 혹은 저장 시 워크스페이스 상태가 초기화 되는 문제 해결
- css 클래스 블록 클릭 혹은 select태그로 css 클래스 블록을 선택해도 선택되지 않는 문제 해결
- 이미지의 width와 height를 설정해줬는데 height를 기준으로 사진이 리사이징 되어 비정상적인 크기의 이미지가 생성되는 문제가 있었음
**문제의 이미지**
-리사이징할 너비와 높이를 모두 설정하는 것이 아닌 너비만 설정하여 문제해결 -> 800px로 고정
- 이유 : 워크스페이스 썸네일 기준 약 3배의 업스케일링이 적용되어 800px로 고정했습니다.
**해결 후 썸네일**
- iframe의 document만 캡처할 경우 `html2canvas`의 한계인지 폰트 및 다른 css들이 적용되지 않는 문제가 발생
**문제의 썸네일**
**해결 방법**
1. 직접 canvas를 생성하고 해당 canvas에 iframe의 document의 모든 요소를 그리는 방식
- 너무 비효율적이고 CSS를 모두 적용하기에는 무리가 있었음
- 또한 flex나 grid는 직접 path 값을 계산해야되는 문제가 있었음
2. div 요소를 만든 뒤 해당 요소의 innerhtml를 조작하여 iframe document 요소를 삽입하고 body의 자식 요소로 만들어 캡처 후 remove하는 방식
- 직접 DOM 조작이라는 문제가 있지만 canvas에다가 직접 그리는 방식에 비해 …
> [#202] 워크스페이스 목록에서 샘플 이미지 깨지는 문제 해결, 미리보기 캡처 시 css 적용 안되는 문제 해결 및 자잘한 버그 해결

- apps/client/src/widgets/workspace/CoachMark/CoachMark.tsx
- 워크스페이스 처음 생성시 에러 해결
워크스페이스 내 툴박스 렌더링 되기 전에 CoachMark에서 관련 메서드를 호출해서 발생한 에러였습니다.
```typescript
useEffect(() => {
const workspace = Blockly.getMainWorkspace() as Blockly.WorkspaceSvg;
if (!workspace) { // 예외처리
return;
}
const toolbox = workspace.getToolbox() as TabbedToolbox;
if (!toolbox) return;
switch (currentStep) {
case 0:
toolbox.clickTab('html');
break;
case 1:
toolbox.clickTab('css');
break;
case 2:
toolbox.clickTab('html');
}
...
}, [currentStep, toolboxDiv]);
``` 
- 화면 가로가 작은 경우 코치마크 4단계일 때 겹치는 문제 해결해야 합니다 #220
> [HOTFIX] 워크스페이스 처음 생성시 에러 해결

- apps/client/src/entities/index.ts
- apps/client/src/entities/workspace/CodeExportButton/CodeExportButton.stories.tsx
- apps/client/src/entities/workspace/CodeExportButton/CodeExportButton.tsx
- apps/client/src/entities/workspace/ImageTagModalList/ImageTagModalList.tsx
- apps/client/src/shared/store/index.ts
- apps/client/src/shared/store/useIframeStore.ts
- apps/client/src/shared/utils/capturePreview.ts
- apps/client/src/shared/utils/exportPreviewHtml.ts
- apps/client/src/shared/utils/iframeErrorMessage.ts
- apps/client/src/shared/utils/index.ts
- apps/client/src/widgets/workspace/PreviewBox/PreviewBox.tsx
- apps/client/src/widgets/workspace/WorkspaceHeaderButtons/WorkspaceHeaderButtons.tsx
- apps/server/src/services/workspaceService.ts
- 코드 내보내기 기능 추가
- 코드 내보내기 버튼 추가
```ts
import { create } from 'zustand';
type TIframe = {
iframeRef: React.RefObject<HTMLIFrameElement> | null;
setIframeRef: (ref: React.RefObject<HTMLIFrameElement>) => void;
};
export const useIframeStore = create<TIframe>((set) => ({
iframeRef: null,
setIframeRef: (ref) => set({ iframeRef: ref }),
}));
```
- iframe document를 그대로 다운 받는 기능 추가
- 다운로드된 파일이름은 워크스페이스 이름.html 으로 설정
- 워크스페이스 header에 추가
> [#223] 코드 내보내기 버튼 추가

- apps/client/src/core/styleFlyout.ts
- CSS 변경사항 감지 로직 변경
- reset css 버튼을 누를 때 감지하도록 변경
**변경 전**
```ts
resetCssCheckboxElement.checked = useResetCssStore.getState().isResetCssChecked;
useWorkspaceChangeStatusStore.getState().setIsCssChanged(true);
resetCssCheckboxElement.addEventListener('change', () => {
useResetCssStore.getState().toggleResetCss();
});
```
**변경 후**
```ts
resetCssCheckboxElement.checked = useResetCssStore.getState().isResetCssChecked;
resetCssCheckboxElement.addEventListener('change', () => {
useResetCssStore.getState().toggleResetCss();
useWorkspaceChangeStatusStore.getState().setIsCssChanged(true);
});
```
> [HOTFIX] CSS 변경사항 감지 로직 변경

- apps/client/src/widgets/workspace/WorkspaceContent/WorkspaceContent.tsx
- css 클래스 블록을 전부 불러오지 못하는 문제 해결
**기존**
```ts
useEffect(() => {
if (!workspace || !canvasInfo || canvasInfo.length === 0) {
return;
}
Blockly.serialization.workspaces.load(JSON.parse(canvasInfo), workspace);
}, [workspace, canvasInfo]);
```
**변경**
```ts
useEffect(() => {
if (!workspace || !canvasInfo || canvasInfo.length === 0) {
return;
}
Blockly.serialization.workspaces.load(JSON.parse(canvasInfo), workspace);
cssStyleToolboxConfig.contents.length = 0;
Object.keys(totalCssPropertyObj).forEach((className) => {
cssStyleToolboxConfig.contents.push({
type: className,
kind: 'block',
enabled: true,
});
});
}, [workspace, canvasInfo]);
```
- 클래스 블록을 강제로 초기화해줬습니다.
> [hotfix] 워크스페이스 페이지 조회 시 css클래스 블록을 전부 불러오지 못하는 문제 해결

- apps/client/src/core/styleFlyout.ts
- CSS 클래스 블록 추가 시 CSS 속성 관련 상태 추가 로직 변경
- 변경 전
-  생성하려는 클래스 블록이 기존에 정의 되어 있지 않을 때만 totalPropsStore 객체에 추가했음
```ts
if (!Blockly.Blocks[createClassType!]) {
useCssPropsStore.getState().addNewCssClass(createClassType);
useWorkspaceChangeStatusStore.getState().setIsBlockChanged(true);
Blockly.Blocks[createClassType!] = {
init: function () {
this.appendDummyInput().appendField(
new CustomFieldLabelSerializable(inputValue!),
'CLASS'
);
this.setOutput(true);
this.setStyle(`defaultBlockCss`);
},
};
}
```
- 변경 후
- CSS 클래스 블록이 정의 되어 있어도 추가하는 로직으로 변경
```ts
if (!Blockly.Blocks[createClassType!]) {
Blockly.Blocks[createClassType!] = {
init: function () {
this.appendDummyInput().appendField(
new CustomFieldLabelSerializable(inputValue!),
'CLASS'
);
this.setOutput(true); …
```
> 🐛 fix: css클래스 삭제 후 똑같은 이름으로 생성 후 css 부여 시 에러 발생하는 버그 수정

- apps/client/src/core/tabbedToolbox.ts
- 툴박스 카테고리가 선택 안되는 문제 해결
- `onClick()` 메서드 수정
```ts
protected onClick_(e: PointerEvent): void {
const element = e.target as HTMLElement;
if (element.tagName === 'INPUT') {
return;
}
if (element.textContent === '컨테이너') {
this.setSelectedItem(this.getToolboxItems()![0]);
return;
}
if (element.textContent === '텍스트') {
this.setSelectedItem(this.getToolboxItems()![1]);
return;
}
if (element.textContent === '폼') {
this.setSelectedItem(this.getToolboxItems()![2]);
return;
}
if (element.textContent === '표') {
this.setSelectedItem(this.getToolboxItems()![3]);
return;
}
if (element.textContent === '리스트') {
this.setSelectedItem(this.getToolboxItems()![4]);
return;
}
if (element.textContent === '링크') {
this.setSelectedItem(this.getToolboxItems()![5]);
return;
}
if (element.textContent === '내용') { …
```
> [HOTFIX] 툴박스 카테고리가 선택안되는 문제 해결

- apps/client/src/entities/workspace/CodeExportButton/CodeExportButton.tsx
- apps/client/src/pages/Workspacepage/WorkspacePage.tsx
- apps/client/src/shared/store/useCoachMarkStore.ts
- apps/client/src/shared/utils/tags.ts
- apps/client/src/widgets/workspace/CoachMark/CoachMark.tsx
- apps/client/src/widgets/workspace/WorkspacePageHeader/WorkspacePageHeader.tsx
- 사용자 가이드 그만두기 클릭시 전역 상태 초기화
- 디자인 디테일
z-index 해제가 제대로 동작하지 않아 발생한 문제였습니다.
- 그만두기 클릭시 단계 상태값 초기화
3, 4, 5 단계는 상태값 초기화하여 z-index 제대로 리셋되었습니다.
하지만 1, 2 단계는 여전히 z-index가 남아있었습니다.
- 코치마크 외부에서 전역상태 업데이트
문제는 코치마크 동작 제어를 내부에서 했던 점입니다. 코치마크가 닫히면서 하이라이팅 스타일 관련 클래스를 제대로 해제하지 못했던 것입니다.
그래서 관련 로직을 상위에서 동작하도록 하여 해결하였습니다.
> [#240] 사용자 가이드 하이라이팅 컴포넌트가 모달에서도 하이라이팅
